<img src=https://lstms-brainybits.s3.ap-south-1.amazonaws.com/green+logo.png width="300" height="200" style="float: left; margin-right: 8px;">

We believe in empowering individuals with the
knowledge and skills they need to become lifelong
learners. Our self-learning website offers a diverse
range of high-quality, interactive courses.
**All rights reserved to BrainyBits. Unauthorized reproduction or distribution of this content is prohibited.**

# Feature Scaling

In [1]:
#Importing the libraries
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset = pd.read_csv('50_startups.csv')

In [3]:
dataset.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
dataset_numerical = dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']]

In [5]:
dataset_numerical.head()

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [6]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
df_scaled = pd.DataFrame(standard_scaler.fit_transform(dataset_numerical), columns=dataset_numerical.columns)
df_scaled

    R&D Spend  Administration  Marketing Spend    Profit
0    2.016411        0.560753         2.153943  2.011203
1    1.955860        1.082807         1.923600  1.999430
2    1.754364       -0.728257         1.626528  1.980842
3    1.554784       -0.096365         1.422210  1.776627
4    1.504937       -1.079919         1.281528  1.357740
5    1.279800       -0.776239         1.254210  1.127250
6    1.340066        0.932147        -0.688150  1.105481
7    1.245057        0.871980         0.932186  1.096210
8    1.030369        0.986952         0.830887  1.007470
9    1.091819       -0.456640         0.776107  0.946022
10   0.620398       -0.387599         0.149807  0.854847
11   0.593085       -1.065540         0.319834  0.808168
12   0.443260        0.215449         0.320617  0.741155
13   0.402078        0.510179         0.343957  0.558750
14   1.017181        1.269199         0.375742  0.516026
15   0.897913        0.045868         0.419219  0.448720
16   0.094441        0.009118         0.440446  0.375436
17   0.460720        0.855666         0.591017  0.334771
18   0.396725       -0.258465         0.692992  0.307116
19   0.279442        1.159837        -1.743127  0.269773
20   0.055726       -0.269588         0.723926  0.161935
21   0.102724        1.169186         0.732788 -0.017534
22   0.006007        0.051850         0.762376 -0.041613
23  -0.136201       -0.562211         0.774349 -0.082169
24   0.073115       -0.795469        -0.581939 -0.086729
25  -0.199312        0.656489        -0.603517 -0.115493
26   0.035370        0.821718        -0.635835 -0.157367
27  -0.035519        0.235069         1.174271 -0.175542
28  -0.168793        2.210141        -0.767189 -0.218798
29  -0.178609        1.142457        -0.858134 -0.275882
30  -0.258074       -0.205629        -0.990357 -0.302625
31  -0.276958        1.130554        -1.014419 -0.364127
32  -0.226949        0.283924        -1.362450 -0.365524
33  -0.401129       -0.659324         0.029817 -0.381787
34  -0.600682        1.310535        -0.001879 -0.383444
35  -0.609750       -1.308658        -0.045493 -0.389291
36  -0.991570        0.205925        -0.081763 -0.533932
37  -0.652532       -2.525994        -0.115608 -0.552955
38  -1.177178       -1.997270        -0.212785 -0.771497
39  -0.773820       -1.383122        -0.297583 -0.777094
40  -0.989577       -0.100900        -0.315786 -0.846411
41  -1.008534       -1.320796        -0.384552 -0.857466
42  -1.102106       -0.906938        -0.520596 -1.015365
43  -1.281134        0.217682        -1.449605 -1.058960
44  -1.134305        1.206419        -1.509074 -1.173209
45  -1.600350        0.101254        -1.727400 -1.180082
46  -1.593413       -0.199322         0.711122 -1.566922
47  -1.622362        0.507722        -1.743127 -1.740627
48  -1.610433       -2.509409        -1.743127 -1.913212
49  -1.622362       -0.157226        -1.369985 -2.439313

In [7]:
from sklearn.preprocessing import MinMaxScaler
norm_scaler = MinMaxScaler()
df_norm = pd.DataFrame(norm_scaler.fit_transform(dataset_numerical), columns=dataset_numerical.columns)
df_norm

    R&D Spend  Administration  Marketing Spend    Profit
0    1.000000        0.651744         1.000000  1.000000
1    0.983359        0.761972         0.940893  0.997355
2    0.927985        0.379579         0.864664  0.993178
3    0.873136        0.512998         0.812235  0.947292
4    0.859438        0.305328         0.776136  0.853171
5    0.797566        0.369448         0.769126  0.801382
6    0.814128        0.730161         0.270710  0.796490
7    0.788018        0.717457         0.686493  0.794407
8    0.729018        0.741733         0.660500  0.774468
9    0.745906        0.436929         0.646443  0.760661
10   0.616351        0.451506         0.485733  0.740175
11   0.608845        0.308364         0.529362  0.729686
12   0.567670        0.578836         0.529563  0.714629
13   0.556352        0.641066         0.535552  0.673644
14   0.725394        0.801327         0.543708  0.664044
15   0.692617        0.543030         0.554864  0.648921
16   0.471808        0.535270         0.560312  0.632454
17   0.572468        0.714013         0.598948  0.623317
18   0.554881        0.478772         0.625116  0.617103
19   0.522650        0.778236         0.000000  0.608713
20   0.461169        0.476424         0.633053  0.584482
21   0.474084        0.780210         0.635327  0.544157
22   0.447505        0.544293         0.642920  0.538747
23   0.408424        0.414638         0.645992  0.529634
24   0.465947        0.365388         0.297964  0.528609
25   0.391080        0.671958         0.292427  0.522146
26   0.455574        0.706845         0.284134  0.512737
27   0.436093        0.582978         0.748613  0.508654
28   0.399467        1.000000         0.250429  0.498934
29   0.396769        0.774566         0.227092  0.486108
30   0.374931        0.489928         0.193163  0.480099
31   0.369741        0.772053         0.186989  0.466280
32   0.383485        0.593294         0.097683  0.465966
33   0.335617        0.394134         0.454943  0.462312
34   0.280776        0.810055         0.446810  0.461939
35   0.278284        0.257032         0.435618  0.460626
36   0.173353        0.576825         0.426311  0.428126
37   0.266527        0.000000         0.417626  0.423852
38   0.122345        0.111636         0.392690  0.374747
39   0.233194        0.241309         0.370931  0.373489
40   0.173901        0.512041         0.366260  0.357914
41   0.168691        0.254469         0.348614  0.355430
42   0.142976        0.341852         0.313705  0.319951
43   0.093776        0.579307         0.075319  0.310156
44   0.134127        0.788072         0.060059  0.284485
45   0.006049        0.554724         0.004036  0.282940
46   0.007956        0.491260         0.629768  0.196020
47   0.000000        0.640547         0.000000  0.156990
48   0.003278        0.003502         0.000000  0.118211
49   0.000000        0.500148         0.095749  0.000000

# Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split

#Setting the value for X and Y
X = df_norm.drop(['Profit'], axis=1)
y = df_norm['Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
print(X_train.head(), "\n")
print(X_test.head(), "\n")
print(y_train.head(), "\n")
print(y_test.head(), "\n")

    R&D Spend  Administration  Marketing Spend
33   0.335617        0.394134         0.454943
35   0.278284        0.257032         0.435618
26   0.455574        0.706845         0.284134
34   0.280776        0.810055         0.446810
18   0.554881        0.478772         0.625116

    R&D Spend  Administration  Marketing Spend
28   0.399467        1.000000         0.250429
11   0.608845        0.308364         0.529362
10   0.616351        0.451506         0.485733
41   0.168691        0.254469         0.348614
2    0.927985        0.379579         0.864664

33    0.462312
35    0.460626
26    0.512737
34    0.461939
18    0.617103
Name: Profit, dtype: float64

28    0.498934
11    0.729686
10    0.740175
41    0.355430
2     0.993178
Name: Profit, dtype: float64